using System;

namespace Anabi.Common.Utils
{
    public static class Constants
    {
        public const string INVALID_ID = "INVALID_ID";
        public const string NO_STORAGE_SPACES_FOUND = "NO_STORAGE_SPACES_FOUND";

        public const string NAME_NOT_EMPTY = "NAME_NOT_EMPTY";
        public const string NAME_MAX_LENGTH_100 = "NAME_MAX_LENGTH_100";

        public const string CONTACTDATA_MAX_LENGTH_1000 = "CONTACTDATA_MAX_LENGTH_1000";
        public const string DESCRIPTION_MAX_LENGTH_2000 = "DESCRIPTION_MAX_LENGTH_2000";

        public const string ENTITY_IS_REFERENCED_BY_OTHER_ENTITIES = "ENTITY_IS_REFERENCED_BY_OTHER_ENTITIES";

        public const string IDENTIFIER_MAX_LENGTH_100 = "IDENTIFIER_MAX_LENGTH_100";
        public const string STAGE_INVALID_ID = "STAGE_INVALID_ID";
        public const string CATEGORY_INVALID_ID = "CATEGORY_INVALID_ID";


        public const string NO_IDENTIFIERS_FOUND = "NO_IDENTIFIERS_FOUND";
        public const string REMARKS_MAX_LENGTH_2000 = nameof(REMARKS_MAX_LENGTH_2000);

        public const string IDNUMBER_MAX_LENGTH_6 = nameof(IDNUMBER_MAX_LENGTH_6);
        public const string IDSERIE_MAX_LENGTH_2 = nameof(IDSERIE_MAX_LENGTH_2);
        public const string IDENTIFICATION_MAX_LENGTH_20 = nameof(IDENTIFICATION_MAX_LENGTH_20);
        public const string PERSONNAME_MAX_LENGTH_200 = nameof(PERSONNAME_MAX_LENGTH_200);
        public const string FIRSTNAME_MAX_LENGTH_50 = nameof(FIRSTNAME_MAX_LENGTH_50);
        public const string NATIONALITY_MAX_LENGTH_20 = nameof(NATIONALITY_MAX_LENGTH_20);

        public const string IDENTIFICATION_CANNOT_BE_EMPTY = nameof(IDENTIFICATION_CANNOT_BE_EMPTY);
        public const string PERSONNAME_CANNOT_BE_EMPTY = nameof(PERSONNAME_CANNOT_BE_EMPTY);
        public const string PERSONIDENTIFICATION_ALREADY_EXISTS = nameof(PERSONIDENTIFICATION_ALREADY_EXISTS);


        public const string MEASUREUNIT_MAX_LENGTH_10 = "MEASUREUNIT_MAX_LENGTH_10";
        public const string QUANTITY_MUST_BE_GREATER_THAN_ZERO = "QUANTITY_MUST_BE_GREATER_THAN_ZERO";


        public const string ESTIMATED_AMOUNT_GREATER_THAN_ZERO = "ESTIMATED_AMOUNT_GREATER_THAN_ZERO";
        public const string ESTIMATED_AMT_CURRENCY_THREE_CHARS = "ESTIMATED_AMT_CURRENCY_THREE_CHARS";
        public const string ASSET_INVALID_ID = nameof(ASSET_INVALID_ID);
        public const string INSTITUTION_DOES_NOT_EXIST = nameof(INSTITUTION_DOES_NOT_EXIST);
        public const string IDENTIFIER_NOT_EMPTY = nameof(IDENTIFIER_NOT_EMPTY);

        public const string DECISION_INVALID_ID = nameof(DECISION_INVALID_ID);
        public const string INSTITUTION_INVALID_ID = nameof(INSTITUTION_INVALID_ID);
        public const string RECOVERYBENEFICIARY_INVALID_ID = nameof(RECOVERYBENEFICIARY_INVALID_ID);
        public const string DECISION_DECISIONNUMBER_INVALID = nameof(DECISION_DECISIONNUMBER_INVALID);

        public const string DECISION_DECISIONDATE_INVALID = nameof(DECISION_DECISIONDATE_INVALID);

        public const string SOLUTION_FILENUMBER_INVALID = nameof(SOLUTION_FILENUMBER_INVALID);
        public const string SOLUTION_FILENUMBERPARQUET_INVALID = nameof(SOLUTION_FILENUMBERPARQUET_INVALID);
        public const string SOLUTION_RECEIVINGDATE_INVALID = nameof(SOLUTION_RECEIVINGDATE_INVALID);

        public const string RECOVERY_PERSONRESPONSIBLE_INVALID = nameof(RECOVERY_PERSONRESPONSIBLE_INVALID);

        public const string RECOVERY_ESTIMATEDAMOUNT_GREATER_THAN_ZERO = nameof(RECOVERY_ESTIMATEDAMOUNT_GREATER_THAN_ZERO);
        public const string RECOVERY_ESTIMATEDAMOUNTCURRENCY_3_CHARS = nameof(RECOVERY_ESTIMATEDAMOUNTCURRENCY_3_CHARS);

        public const string RECOVERY_ACTUALAMOUNT_GREATER_THAN_ZERO = nameof(RECOVERY_ACTUALAMOUNT_GREATER_THAN_ZERO);
        public const string RECOVERY_ACTUALAMOUNTCURRENCY_3_CHARS = nameof(RECOVERY_ACTUALAMOUNTCURRENCY_3_CHARS);

        public const string RECOVERY_RECOVERYCOMMITTEEPRESIDENT_MAX_LENGTH_200 = nameof(RECOVERY_RECOVERYCOMMITTEEPRESIDENT_MAX_LENGTH_200);
        public const string RECOVERY_EVALUATIONCOMMITTEEPRESIDENT_MAX_LENGTH_200 = nameof(RECOVERY_EVALUATIONCOMMITTEEPRESIDENT_MAX_LENGTH_200);
        public const string PRECAUTIONARYMEASURE_INVALID_ID = nameof(PRECAUTIONARYMEASURE_INVALID_ID);

        public const string COUNTY_INVALID_ID = nameof(COUNTY_INVALID_ID);
        public const string ADDRESS_STREET_INVALID_NAME = nameof(ADDRESS_STREET_INVALID_NAME);
        public const string ADDRESS_CITY_INVALID_NAME = nameof(ADDRESS_CITY_INVALID_NAME);
        public const string ADDRESS_BUILDING_INVALID_NUMBER = nameof(ADDRESS_BUILDING_INVALID_NUMBER);
        public const string ADDRESS_STAIR_INVALID_NUMBER = nameof(ADDRESS_STAIR_INVALID_NUMBER);
        public const string ADDRESS_FLOOR_INVALID_NUMBER = nameof(ADDRESS_FLOOR_INVALID_NUMBER);
        public const string ADDRESS_DESCRIPTION_INVALID = nameof(ADDRESS_DESCRIPTION_INVALID);
        public const string STORAGE_SPACE_TYPE_NOT_EMPTY = nameof(STORAGE_SPACE_TYPE_NOT_EMPTY);

        public const string ASSET_ID_MUST_BE_SPECIFIED = nameof(ASSET_ID_MUST_BE_SPECIFIED);
        public const string DEFENDANT_ID_MUST_BE_SPECIFIED = nameof(DEFENDANT_ID_MUST_BE_SPECIFIED);
        public const string DEFENDANT_INVALID_ID = nameof(DEFENDANT_INVALID_ID);
        public const string ASSET_DEFENDANT_INVALID_IDS = nameof(ASSET_DEFENDANT_INVALID_IDS);
    }
}
